nguage: c
script:
- pwd
- ls
- cd ConsoleTest
- pwd
- g++ -v
- echo "start build program"
- g++ test.cpp -o exe
deploy:
  provider: releases
  file: "test.exe" 
  file_glob: true
  skip_cleanup: true
  on: 
     branch: master
