language: c
script:
- pwd
- ls
- cd ConsoleTest
- pwd
- g++ -v
- echo "start build program"
- g++ test.cpp -o exe
- ./exe
- pwd
deploy:
  provider: releases
  user: "tlglovewf"
  password: "tlglove326"
  file: ConsoleTest/exe
  skip_cleanup: true
  on:
    repo: tlglovewf/CppTest
