nguage: c
script:
- cd ConsoleTest
- gcc test.cpp -o exe
before_deploy:
- export RELEASE_EXE=$(ls /output/test.exe)
- echo "deploying output"
deploy:
  provider: releases
  file: "${RELEASE_PKG_FILE}" 
  file_glob: true
  skip_cleanup: true
  on: 
     branch: master
