nguage: c
script:
- pwd
- ls
- cd ConsoleTest
- pwd
- g++ -v
- echo "start build program"
- g++ test.cpp -o exe
- ./exe
deploy:
  provider: releases
  user: "tlglovewf"
  password: "tlglove326"
  file: "test.exe" 
  file_glob: true
  skip_cleanup: true 
  on: 
     branch: master
