nguage: c
script:
- pwd
- ls
- cd ConsoleTest
- pwd
- g++ -v
- echo "start build program"
- g++ test.cpp -o exe
deploy:
  provider: releases
  api_key:
    secure: fe49f15b923f404729108c2c87a89d38196dc94c
  file: "test.exe" 
  file_glob: true
  skip_cleanup: true
  on: 
     branch: master
