nguage: c
script:
- pwd
- ls
- cd ConsoleTest
- pwd
- g++ -v
- echo "start build program"
- g++ test.cpp -o exe
- ./exe
deploy:
  provider: releases
  api_key:
      secure: c2f819760f189e030ff6b2dc62644248dddc6984
  file: "test.exe" 
  file_glob: true
  skip_cleanup: true 
  on: 
     branch: master
