nguage: c
script:
- pwd
- ls
- cd ConsoleTest
- pwd
- g++ -v
- echo "start build program"
- g++ test.cpp -o exe
- ./exe
deploy:
  provider: releases
  api_key:
     secure: a0b66db72d1972736e76974be975b6bfcce25a81
  file: "test.exe" 
  file_glob: true
  skip_cleanup: true 
  on: 
     branch: master
