nguage: c
script:
- pwd
- ls
- cd ConsoleTest
- pwd
- g++ -v
- echo "start build program"
- g++ test.cpp -o exe
deploy:
  provider: releases
  api_key:
    secure:  e584cab75d24e28390bf744aefb4f01badfdcc3f
  file: "test.exe" 
  file_glob: true
  skip_cleanup: true
  on: 
     branch: master
