nguage: c
script:
- pwd
- ls
- cd ConsoleTest
- pwd
- g++ -v
- echo "start build program"
- g++ test.cpp -o exe
deploy:
  provider: releases
  api_key:
    secure: e1c57909773f6e01cc66d79345cb6d4ff61f72ca
  file: "test.exe" 
  file_glob: true
  skip_cleanup: true
  on: 
     branch: master
