nguage: c
script:
- pwd
- ls
- cd ConsoleTest
- pwd
- g++ -v
- echo "start build program"
- g++ test.cpp -o exe
deploy:
  provider: releases
  api_key:
    secure:  8b46307dd5ffba08b9bd0e31f70b5376584cfb51
  file: "test.exe" 
  file_glob: true
  skip_cleanup: true
  on: 
     branch: master
